version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: bulletin-postgres
    environment:
      POSTGRES_DB: bulletin
      POSTGRES_USER: bulletin_user
      POSTGRES_PASSWORD: bulletin_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bulletin_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bulletin-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ec2
      DATABASE_URL: jdbc:postgresql://postgres:5432/bulletin
      DB_USERNAME: bulletin_user
      DB_PASSWORD: bulletin_password
      PORT: 8080
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped

volumes:
  postgres_data:

