[phases.setup]
nixPkgs = ['...', 'gradle']

[phases.build]
cmds = ['./gradlew clean bootJar --no-daemon']

[start]
cmd = 'java -Dserver.port=$PORT -Dspring.profiles.active=railway -jar build/libs/*.jar'
