[phases.setup]
nixPkgs = ['jdk17', 'gradle']

[phases.build]
cmds = [
    'export JAVA_HOME=/usr/lib/jvm/java-17-openjdk',
    'export PATH=$JAVA_HOME/bin:$PATH',
    'chmod +x ./gradlew',
    './gradlew clean build -x test --no-daemon'
]

[start]
cmd = 'java -Dserver.port=$PORT -Dspring.profiles.active=railway -jar $(ls build/libs/*.jar | head -1)'
