[phases.setup]
nixPkgs = ['jdk17', 'gradle']

[phases.build]
cmds = ['chmod +x ./gradlew', './gradlew clean bootJar --no-daemon']

[start]
cmd = 'java -Dserver.port=$PORT -Dspring.profiles.active=railway -jar $(ls build/libs/*.jar | head -1)'
