[build]
builder = "dockerfile"

[deploy]
startCommand = "java -Dserver.port=$PORT -jar app.jar"
healthcheckPath = "/api/bulletin/today"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "bulletin"
