spring:
  # 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:testdb  # 개발용 H2 인메모리 DB
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # JPA/Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: create-drop  # 개발용 (운영시 validate로 변경)
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        
  # H2 Console 활성화 (개발용)
  h2:
    console:
      enabled: true
      path: /h2-console
      
  # Thymeleaf 설정
  thymeleaf:
    cache: false  # 개발용 (운영시 true로 변경)
    prefix: classpath:/templates/
    suffix: .html
    
  # Security 기본 설정
  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

# 서버 설정
server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 로깅 설정
logging:
  level:
    com.church.bulletin: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# API 문서화 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

---
# 운영 환경 설정
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/church_bulletin?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:church_user}
    password: ${DB_PASSWORD:church_password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  thymeleaf:
    cache: true
  h2:
    console:
      enabled: false

server:
  port: ${SERVER_PORT:80}

logging:
  level:
    com.church.bulletin: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
